apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:4.2
          name: mongo
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-hostpath0
      restartPolicy: Always
      volumes:
        - name: mongo-hostpath0
          emptyDir: {}
status: {}
